# Generated by Django 3.1.7 on 2021-06-18 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patinador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patinador',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='patinador',
            old_name='estutus',
            new_name='estatus',
        ),
        migrations.AddField(
            model_name='patinador',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Patinador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='patinador',
            index=models.Index(fields=['created_at'], name='patinador_p_created_0e7855_idx'),
        ),
    ]
