# Generated by Django 3.1.7 on 2022-03-22 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patinador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patinador',
            name='created_atv',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
