# Generated by Django 3.1.7 on 2022-05-07 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patinador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patinador',
            name='btnAcci',
            field=models.CharField(default='<button type="button" class="btn btn-outline-warning text-center btn-sm btn-block ">Accion</button>', max_length=97),
        ),
        migrations.AlterField(
            model_name='patinador',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patinador', to='authapp.myuser'),
        ),
    ]
