# Generated by Django 3.1.7 on 2021-05-05 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0001_initial'),
        ('patinador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patinador',
            name='nom_patinador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patinador', to='integrante.integrante'),
        ),
    ]
