# Generated by Django 4.0.5 on 2022-06-15 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0001_initial'),
        ('empresa', '0001_initial'),
        ('patinador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patinador',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
        ),
        migrations.AlterField(
            model_name='patinador',
            name='integrante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='integrante.integrante'),
        ),
    ]
