# Generated by Django 4.0.4 on 2022-05-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patinador', '0002_patinador_fecha_cierre_alter_patinador_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='patinador',
            name='ctrlProduccion',
            field=models.BooleanField(default=False),
        ),
    ]
