# Generated by Django 3.1.7 on 2021-06-29 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0002_auto_20210628_2343'),
        ('patinador', '0002_auto_20210629_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patinador',
            name='integrante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Patinador', to='integrante.integrante'),
        ),
    ]
