# Generated by Django 3.1.7 on 2022-05-01 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0001_initial'),
        ('patinador', '0002_patinador_ctrldespacho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patinador',
            name='integrante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Patinador', to='integrante.integrante'),
        ),
    ]
