# Generated by Django 3.1.7 on 2021-06-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patinador', '0002_auto_20210617_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='patinador',
            name='btnAcci',
            field=models.CharField(blank=True, default='<button type="button" class="btn btn-outline-light text-center btn-sm btn-block ">Accion</button>', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patinador',
            name='btnInfo',
            field=models.CharField(blank=True, default='<button type="button" class="btn btn-outline-light text-center btn-sm btn-block">Info</button>', max_length=30, null=True),
        ),
    ]
