# Generated by Django 4.0.5 on 2022-06-15 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patinador', '0002_alter_patinador_empresa_alter_patinador_integrante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patinador',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
