# Generated by Django 4.0.4 on 2022-05-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patinador', '0003_patinador_ctrlproduccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patinador',
            name='fecha_cierre',
        ),
        migrations.AddField(
            model_name='patinador',
            name='ctrlCasino',
            field=models.BooleanField(default=False),
        ),
    ]
