# Generated by Django 3.1.7 on 2021-06-19 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patinador', '0003_auto_20210618_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patinador',
            name='btnInfo',
        ),
    ]
