# Generated by Django 4.0.4 on 2022-05-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patinador', '0004_remove_patinador_fecha_cierre_patinador_ctrlcasino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patinador',
            name='btnAcci',
            field=models.CharField(default='<button type="button" class="btn btn-outline-warning text-center btn-sm btn-block ">Accion</button>', max_length=150),
        ),
    ]
