# Generated by Django 3.1.7 on 2021-07-11 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operacion', '0007_auto_20210711_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_talla', models.CharField(max_length=20, unique=True)),
                ('nota', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('num_talla', models.IntegerField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Talla', to='empresa.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Talla', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CanTalla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_talla', models.IntegerField(blank=True, null=True)),
                ('res_talla', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CanTalla', to='empresa.empresa')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CanTalla', to='operacion.operacion')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CanTalla', to='talla.talla')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CanTalla', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='talla',
            index=models.Index(fields=['created_at'], name='talla_talla_created_f87627_idx'),
        ),
        migrations.AddIndex(
            model_name='cantalla',
            index=models.Index(fields=['created_at'], name='talla_canta_created_e08e0e_idx'),
        ),
    ]
