# Generated by Django 3.1.7 on 2022-05-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talla',
            name='btnAddTalla',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
