# Generated by Django 3.1.7 on 2021-07-11 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talla', '0002_talla_btnacci'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talla',
            name='nota',
        ),
    ]
