# Generated by Django 3.1.7 on 2021-07-18 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talla', '0002_auto_20210717_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantalla',
            name='talla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CanTalla', to='talla.talla'),
        ),
    ]
