# Generated by Django 3.1.7 on 2022-05-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talla', '0002_talla_btnaddtalla'),
    ]

    operations = [
        migrations.AddField(
            model_name='talla',
            name='inputNameTalla',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
