# Generated by Django 3.1.7 on 2021-07-13 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talla', '0003_remove_talla_nota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cantalla',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='talla',
            options={'ordering': ['created_at']},
        ),
    ]
