# Generated by Django 3.1.7 on 2022-02-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talla', '0003_auto_20210717_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talla',
            name='nom_talla',
            field=models.CharField(max_length=20),
        ),
    ]
