# Generated by Django 3.1.7 on 2022-05-04 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talla', '0003_talla_inputnametalla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talla',
            name='inputNameTalla',
        ),
    ]
