# Generated by Django 3.1.7 on 2022-02-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talla', '0004_auto_20220217_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talla',
            name='nom_talla',
            field=models.CharField(max_length=10),
        ),
    ]
