# Generated by Django 4.0.5 on 2022-06-25 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0001_initial'),
        ('integrante', '0001_initial'),
        ('patinador', '0001_initial'),
        ('talla', '0001_initial'),
        ('acumulado', '0001_initial'),
        ('tarea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proacumulado',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='proacumulado',
            name='integrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrante.integrante'),
        ),
        migrations.AddField(
            model_name='proacumulado',
            name='patinador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patinador.patinador'),
        ),
        migrations.AddField(
            model_name='proacumulado',
            name='talla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talla.talla'),
        ),
        migrations.AddField(
            model_name='proacumulado',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarea.tarea'),
        ),
        migrations.AddField(
            model_name='proacumulado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acumulado',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='acumulado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='proacumulado',
            index=models.Index(fields=['created_at'], name='acumulado_p_created_11753f_idx'),
        ),
        migrations.AddIndex(
            model_name='acumulado',
            index=models.Index(fields=['created_at'], name='acumulado_a_created_270ee2_idx'),
        ),
    ]
