# Generated by Django 4.0.4 on 2022-05-22 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_remove_relacionempresa_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acumulado', '0003_alter_acumulado_empresa_alter_acumulado_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcAcomulado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='acumulado',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='acumulado',
            name='btnAcci',
            field=models.CharField(default='<button type="button" class="btn btn-outline-warning text-center btn-sm btn-block ">Accion</button>', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='acumulado',
            name='btnInfo',
            field=models.CharField(default='<button type="button" class="btn btn-outline-info text-center btn-sm btn-block ">Info</button>', max_length=300, null=True),
        ),
        migrations.AddIndex(
            model_name='acumulado',
            index=models.Index(fields=['created_at'], name='acumulado_a_created_270ee2_idx'),
        ),
        migrations.AddField(
            model_name='procacomulado',
            name='acumulado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acumulado.acumulado'),
        ),
        migrations.AddField(
            model_name='procacomulado',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='procacomulado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='procacomulado',
            index=models.Index(fields=['created_at'], name='acumulado_p_created_3565c6_idx'),
        ),
    ]
