# Generated by Django 4.0.4 on 2022-05-22 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0004_alter_integrante_cedula'),
        ('talla', '0003_alter_cantalla_usuario'),
        ('acumulado', '0004_procacomulado_alter_acumulado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procacomulado',
            name='integrante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='integrante.integrante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procacomulado',
            name='talla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talla.talla'),
        ),
    ]
