# Generated by Django 4.0.4 on 2022-05-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acumulado', '0005_procacomulado_integrante_procacomulado_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='procacomulado',
            name='can_Proacumulado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
