# Generated by Django 4.0.4 on 2022-05-22 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acumulado', '0006_procacomulado_can_proacumulado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procacomulado',
            old_name='can_Proacumulado',
            new_name='can_prod_acum',
        ),
    ]
