# Generated by Django 4.0.4 on 2022-05-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acumulado', '0007_rename_can_proacumulado_procacomulado_can_prod_acum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acumulado',
            name='can_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
