# Generated by Django 4.0.4 on 2022-05-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acumulado', '0008_alter_acumulado_can_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='acumulado',
            name='nota',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
