# Generated by Django 4.0.4 on 2022-05-22 22:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0004_alter_integrante_cedula'),
        ('talla', '0003_alter_cantalla_usuario'),
        ('empresa', '0004_rename_usuario_cambioempres_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acumulado', '0010_acumulado_delacumulado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcAcomulado',
            new_name='ProAcumulado',
        ),
        migrations.RemoveIndex(
            model_name='proacumulado',
            name='acumulado_p_created_3565c6_idx',
        ),
        migrations.AddIndex(
            model_name='proacumulado',
            index=models.Index(fields=['created_at'], name='acumulado_p_created_11753f_idx'),
        ),
    ]
