# Generated by Django 4.0.4 on 2022-05-22 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patinador', '0004_remove_patinador_fecha_cierre_patinador_ctrlcasino'),
        ('acumulado', '0011_rename_procacomulado_proacumulado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proacumulado',
            name='patinador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patinador.patinador'),
            preserve_default=False,
        ),
    ]
