# Generated by Django 4.0.4 on 2022-05-22 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0005_remove_tarea_codigo_tarea'),
        ('acumulado', '0012_proacumulado_patinador'),
    ]

    operations = [
        migrations.AddField(
            model_name='proacumulado',
            name='tarea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tarea.tarea'),
            preserve_default=False,
        ),
    ]
