# Generated by Django 4.0.4 on 2022-05-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acumulado', '0015_alter_acumulado_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proacumulado',
            name='delAcumulProc',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
