# Generated by Django 4.0.4 on 2022-05-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acumulado', '0017_remove_acumulado_can_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acumulado',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proacumulado',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
