# Generated by Django 4.0.4 on 2022-05-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acumulado', '0018_acumulado_fecha_cierre_proacumulado_fecha_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='proacumulado',
            name='estatus',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, null=True),
        ),
    ]
