# Generated by Django 4.0.4 on 2022-05-31 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acumulado', '0019_proacumulado_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acumulado',
            name='delAcumulado',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
