# Generated by Django 4.0.4 on 2022-06-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acumulado', '0020_alter_acumulado_delacumulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='acumulado',
            name='costeAcu',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
