# Generated by Django 3.1.7 on 2022-05-12 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('deuda', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('btnInfo', models.CharField(blank=True, default='<button type="button" class="btn btn-outline-info icofont-info-squar text-center btn-md btn-block">Info</button>', max_length=1000, null=True)),
                ('btnAcci', models.CharField(blank=True, default='<button type="button" class="btn btn-outline-warning icofont-settings-al text-center btn-md btn-block ">Accion</button>', max_length=1000, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Casino', to='empresa.empresa')),
                ('integrante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Casino', to='integrante.integrante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Casino', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Importe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Importe', to='casino.casino')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Importe', to='empresa.empresa')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='importe',
            index=models.Index(fields=['created_at'], name='casino_impo_created_f650af_idx'),
        ),
        migrations.AddIndex(
            model_name='casino',
            index=models.Index(fields=['created_at'], name='casino_casi_created_00d07e_idx'),
        ),
    ]
