# Generated by Django 3.1.7 on 2022-05-07 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Casino', to=settings.AUTH_USER_MODEL),
        ),
    ]
