# Generated by Django 3.1.7 on 2021-04-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casino',
            options={},
        ),
    ]
