# Generated by Django 3.1.7 on 2021-07-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='btnAcci',
            field=models.CharField(blank=True, default='\n   <button type="button" class="btn btn-outline-info icofont-dollar-true text-center btn-sm btn-block">Info</button>\'\n    ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='casino',
            name='btnInfo',
            field=models.CharField(blank=True, default='\n    <button type="button" class="btn btn-outline-info icofont-info-square text-center btn-sm btn-block">Info</button>\n    ', max_length=1000, null=True),
        ),
    ]
