# Generated by Django 3.1.7 on 2021-05-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casino',
            name='user',
        ),
        migrations.AddField(
            model_name='casino',
            name='deuda',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
