# Generated by Django 4.0.4 on 2022-05-23 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0004_alter_integrante_cedula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0004_rename_usuario_cambioempres_usuario_and_more'),
        ('casino', '0002_casino_estatus_importe_estatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casino',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='deuda',
        ),
        migrations.AlterField(
            model_name='casino',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='integrante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='integrante.integrante'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Importe',
        ),
    ]
