# Generated by Django 3.1.7 on 2021-07-06 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0001_initial'),
        ('casino', '0002_auto_20210704_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='btnAcci',
            field=models.CharField(blank=True, default='<button type="button" class="btn btn-outline-info icofont-dollar-true text-center btn-sm btn-block"></button>', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='casino',
            name='btnInfo',
            field=models.CharField(blank=True, default='<button type="button" class="btn btn-outline-info icofont-info-square text-center btn-sm btn-block"></button>', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='casino',
            name='deuda',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='casino',
            name='integrante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Casino', to='integrante.integrante'),
        ),
    ]
