# Generated by Django 4.0.4 on 2022-05-23 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0003_remove_casino_cantidad_remove_casino_deuda_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Casino',
        ),
    ]
