# Generated by Django 4.0.4 on 2022-05-23 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patinador', '0004_remove_patinador_fecha_cierre_patinador_ctrlcasino'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrante', '0004_alter_integrante_cedula'),
        ('empresa', '0004_rename_usuario_cambioempres_usuario_and_more'),
        ('casino', '0004_delete_casino'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_casino', models.CharField(max_length=35, unique=True)),
                ('can_total', models.IntegerField(blank=True, default=0, null=True)),
                ('btnccion', models.CharField(default='<button type="button" class="btn btn-outline-warning text-center btn-sm btn-block ">Accion</button>', max_length=300, null=True)),
                ('btnInfo', models.CharField(default='<button type="button" class="btn btn-outline-info text-center btn-sm btn-block ">Info</button>', max_length=300, null=True)),
                ('estatus', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Importe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('estatus', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casino.casino')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrante.integrante')),
                ('patinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patinador.patinador')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='importe',
            index=models.Index(fields=['created_at'], name='casino_impo_created_f650af_idx'),
        ),
        migrations.AddIndex(
            model_name='casino',
            index=models.Index(fields=['created_at'], name='casino_casi_created_00d07e_idx'),
        ),
    ]
