# Generated by Django 4.0.4 on 2022-05-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='nota_casino',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
