# Generated by Django 4.0.4 on 2022-05-24 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0006_casino_nota_casino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casino',
            name='nota_casino',
        ),
    ]
