# Generated by Django 4.0.4 on 2022-05-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0008_importe_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importe',
            name='estatus',
        ),
    ]
