# Generated by Django 3.1.7 on 2022-03-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencia',
            name='nom_referencia',
            field=models.CharField(max_length=30),
        ),
    ]
