# Generated by Django 3.1.7 on 2021-07-16 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencia',
            name='fotoPrendaDos',
        ),
        migrations.RemoveField(
            model_name='referencia',
            name='fotoPrendaUno',
        ),
    ]
