# Generated by Django 4.0.5 on 2022-06-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencia',
            name='fecha_cierre',
        ),
        migrations.AddField(
            model_name='referencia',
            name='btnAcci',
            field=models.CharField(default='<button type="button" class="btn btn-outline-warning text-center btn-sm btn-block ">Accion</button>', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='referencia',
            name='btnInfo',
            field=models.CharField(default='<button type="button" class="btn btn-outline-info text-center btn-sm btn-block ">Info</button>', max_length=300, null=True),
        ),
    ]
