# Generated by Django 3.1.7 on 2021-05-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenda',
            name='user',
        ),
    ]
