"""https://wpdatatables.com/datatables-alternative/
pillow

pip install rest-framework-generic-relations
                                            # pip install django-webpack-loader
django-cors-headers
librerias 
djangorestframework-3.12.1
Django settings for TesPro project.
Generated by 'django-admin startproject' using Django 3.1.7.
For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.


BASE_DIR = Path(__file__).resolve().parent.parent



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'z=d8tk47=)muszj)2j7*cm@7tl!5sh^=c&%kxxp1=)gy%15*2u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
 #   "debug_toolbar",#botarrrar menu debuguer
    #'django_tables2',
    'rest_framework.authtoken',
#    'generic_relations',


#'django_seed',#borrrrrrarrrrr!
    'ajax_select',
   #'crudbuilder',
    'corsheaders',
    'crispy_forms',
    'django.contrib.admin',
    'django.contrib.auth',    
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'empresa',
    'destajo',
    'despacho',
    'segimientoOp',
    'acumulado',
    'xtarea',
    'home',
    'produccion',
    #usuario
    'authapp',
    #rest-framework crud
    'talla',
    'color',
    'tarea',
    'referencia',
    'integrante',
    'patinador',
    'operacion',
    'casino',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],

    
    
    
}

MIDDLEWARE = [
    
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
  #  "debug_toolbar.middleware.DebugToolbarMiddleware",#borarrar menu debuger
    
]
MIDDLEWARE_CLASSES = [
    
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
     
]

ROOT_URLCONF = 'TesPro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join('template')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TesPro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db/db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'es-es'


TIME_ZONE = 'America/Bogota'



#TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]


DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'


SESSION_COOKIE_AGE = 300000
SESSION_EXPIRE_SECONDS = 300000
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True

APPEND_SLASH=False

CORS_ORIGIN_ALLOW_ALL = True
AUTH_USER_MODEL = 'authapp.MyUser'
''' INTERNAL_IPS = [
    # ...
    "127.0.0.1",#borarrar menu debuger
    # ...
] '''