# Generated by Django 4.0.4 on 2022-05-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destajo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destajo',
            name='estatus',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, null=True),
        ),
    ]
