# Generated by Django 4.0.4 on 2022-05-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='patinador',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
