# Generated by Django 3.1.7 on 2021-06-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='nom_color',
            field=models.CharField(max_length=20),
        ),
    ]
