# Generated by Django 3.1.7 on 2021-06-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0002_auto_20210613_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='color',
            index=models.Index(fields=['created_at'], name='color_color_created_7f800b_idx'),
        ),
    ]
