# Generated by Django 3.1.7 on 2022-05-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0002_auto_20220506_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='codigo_color',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
