# Generated by Django 3.1.7 on 2021-05-03 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='email addres')),
                ('cedula', models.IntegerField(blank=True, null=True)),
                ('num_telf', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=150)),
                ('abilidad', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Integrante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombres'],
            },
        ),
    ]
