# Generated by Django 3.1.7 on 2021-05-16 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estutus', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1)),
                ('sexo', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=1)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('cedula', models.IntegerField(blank=True, null=True, unique=True)),
                ('num_telf', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=150)),
                ('abilidad', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Integrante', to='empresa.empresa')),
            ],
            options={
                'ordering': ['nombres'],
            },
        ),
    ]
