# Generated by Django 3.1.7 on 2021-07-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrante',
            name='abilidad',
        ),
    ]
