# Generated by Django 3.1.7 on 2021-06-14 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrante', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integrante',
            old_name='estutus',
            new_name='estatus',
        ),
        migrations.AddField(
            model_name='integrante',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Integrante', to=settings.AUTH_USER_MODEL),
        ),
    ]
