# Generated by Django 3.1.7 on 2022-03-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='cedula',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
