# Generated by Django 3.1.7 on 2022-05-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='direccion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
