# Generated by Django 3.1.7 on 2021-06-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0002_auto_20210613_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='abilidad',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='direccion',
            field=models.CharField(max_length=250),
        ),
    ]
