# Generated by Django 3.1.7 on 2021-05-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0002_auto_20210505_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electronico'),
        ),
    ]
