# Generated by Django 4.0.4 on 2022-05-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0002_alter_integrante_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='cedula',
            field=models.IntegerField(unique=True),
        ),
    ]
