# Generated by Django 3.1.7 on 2022-05-06 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrante', '0003_auto_20220506_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Integrante', to=settings.AUTH_USER_MODEL),
        ),
    ]
