# Generated by Django 3.1.7 on 2022-05-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0004_auto_20220506_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='btnAcci',
            field=models.CharField(default='<button type="button" class="btn btn-outline-warning text-center btn-sm btn-block ">Accion</button>', max_length=100),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='btnInfo',
            field=models.CharField(default='<button type="button" class="btn btn-outline-info text-center btn-sm btn-block">Info</button>', max_length=100),
        ),
    ]
