# Generated by Django 3.1.7 on 2021-06-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0004_auto_20210616_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='btnAcci',
            field=models.CharField(blank=True, default='<a class="btn">+</a>', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='integrante',
            name='btnInfo',
            field=models.CharField(blank=True, default='<a class="btn">+</a>', max_length=30, null=True),
        ),
    ]
