# Generated by Django 3.1.7 on 2021-06-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0005_auto_20210616_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='btnInfo',
            field=models.CharField(blank=True, default='<a class="btn btn-primary">+</a>', max_length=30, null=True),
        ),
    ]
