# Generated by Django 4.0.4 on 2022-05-28 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_rename_usuario_cambioempres_usuario_and_more'),
        ('integrante', '0006_alter_integrante_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
        ),
    ]
