# Generated by Django 4.0.4 on 2022-05-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0007_alter_integrante_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='cedula',
            field=models.IntegerField(unique=True),
        ),
    ]
