# Generated by Django 3.1.7 on 2021-06-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0009_auto_20210616_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='btnAcci',
            field=models.CharField(blank=True, default='<h6>-</h6>', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='btnInfo',
            field=models.CharField(blank=True, default='<h6>+<h6>', max_length=30, null=True),
        ),
    ]
