# Generated by Django 3.1.7 on 2021-06-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0011_auto_20210616_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='btnAcci',
            field=models.CharField(blank=True, default='<h3  class="text-center"><i class="btn-outline-danger icofont-ui-close"></i></h3 >', max_length=30, null=True),
        ),
    ]
