# Generated by Django 3.1.7 on 2021-05-05 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrante', '0001_initial'),
        ('prenda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_terminada', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Despacho', to='integrante.integrante')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Despacho', to='prenda.prenda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Despacho', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
