# Generated by Django 3.1.7 on 2021-07-18 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrante', '0001_initial'),
        ('operacion', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_terminada', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DespachoE', to='empresa.empresa')),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DespachoI', to='integrante.integrante')),
                ('nom_patinador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='DespachoPP', to='integrante.integrante')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DespachoO', to='operacion.operacion')),
            ],
        ),
    ]
