# Generated by Django 3.1.7 on 2022-05-07 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talla', '0005_auto_20220506_2012'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('despacho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='can_terminada',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='talla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Despacho', to='talla.talla'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Despacho', to='authapp.myuser'),
        ),
    ]
