# Generated by Django 3.1.7 on 2022-02-25 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0001_initial'),
        ('despacho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='patinador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DespachoPP', to='integrante.integrante'),
        ),
    ]
