# Generated by Django 3.1.7 on 2021-04-30 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0002_auto_20210430_1349'),
        ('despacho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='integrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Despacho', to='integrante.integrante'),
        ),
    ]
