# Generated by Django 3.1.7 on 2022-04-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='btnDelDespacho',
            field=models.CharField(blank=True, default='-', max_length=300, null=True),
        ),
    ]
