# Generated by Django 3.1.7 on 2022-03-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0002_auto_20220224_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('date', models.DateField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['completed', 'date'],
            },
        ),
    ]
