# Generated by Django 3.1.7 on 2022-03-27 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0002_auto_20220325_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despacho',
            name='can_terminada',
        ),
    ]
