# Generated by Django 4.0.4 on 2022-05-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0002_despacho_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='btnDelDespacho',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
