# Generated by Django 4.0.5 on 2022-06-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0003_alter_despacho_btntareaseg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='btnTareaSeg',
            field=models.CharField(default='<button type="button" class="btn btn-outline-warning text-center btn-sm btn-block ">Tarea</button>', max_length=300),
        ),
    ]
