# Generated by Django 3.1.7 on 2022-03-27 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20220325_2200'),
        ('talla', '0001_initial'),
        ('operacion', '0002_auto_20220325_2020'),
        ('integrante', '0002_auto_20220325_1952'),
        ('despacho', '0004_despacho_can_terminada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Despacho', to='empresa.empresa'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Despacho', to='operacion.operacion'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='patinador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Despacho', to='integrante.integrante'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='talla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Despacho', to='talla.talla'),
        ),
    ]
