# Generated by Django 4.0.5 on 2022-06-30 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0004_alter_despacho_btntareaseg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despacho',
            name='btnTareaSeg',
        ),
    ]
