# Generated by Django 3.1.7 on 2022-03-27 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patinador', '0001_initial'),
        ('despacho', '0005_auto_20220326_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='patinador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Despacho', to='patinador.patinador'),
        ),
    ]
