# Generated by Django 3.1.7 on 2022-03-27 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20220325_2200'),
        ('operacion', '0002_auto_20220325_2020'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patinador', '0001_initial'),
        ('despacho', '0007_auto_20220326_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Despacho', to='empresa.empresa'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Despacho', to='operacion.operacion'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='patinador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Despacho', to='patinador.patinador'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Despacho', to=settings.AUTH_USER_MODEL),
        ),
    ]
