# Generated by Django 3.1.7 on 2022-03-27 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talla', '0001_initial'),
        ('despacho', '0008_auto_20220326_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='talla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Despacho', to='talla.talla'),
        ),
    ]
