# Generated by Django 3.1.7 on 2022-05-12 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talla', '0001_initial'),
        ('operacion', '0001_initial'),
        ('empresa', '0001_initial'),
        ('integrante', '0001_initial'),
        ('patinador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_terminada', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produccion', to='empresa.empresa')),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProduccionI', to='integrante.integrante')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produccion', to='operacion.operacion')),
                ('patinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produccion', to='patinador.patinador')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Produccion', to='talla.talla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produccion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
