# Generated by Django 4.0.4 on 2022-06-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='costeProd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
