# Generated by Django 4.0.4 on 2022-05-15 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0001_initial'),
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='integrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProduccionI', to='integrante.integrante'),
        ),
    ]
