# Generated by Django 4.0.4 on 2022-06-03 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_alter_produccion_costeprod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='costeProd',
        ),
    ]
