# Generated by Django 4.0.4 on 2022-05-19 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talla', '0002_talla_estatus'),
        ('produccion', '0004_produccion_estatus_produccion_fecha_cierre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='talla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ProduccionTallaFK', to='talla.talla'),
        ),
    ]
