# Generated by Django 4.0.4 on 2022-05-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0005_alter_produccion_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='delProduccion',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
