# Generated by Django 4.0.4 on 2022-06-03 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0003_alter_operacion_nota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patinador', '0005_alter_patinador_btnacci'),
        ('empresa', '0005_alter_empresa_nom_empresa'),
        ('tarea', '0005_remove_tarea_codigo_tarea'),
        ('produccion', '0006_alter_produccion_delproduccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.operacion'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='patinador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patinador.patinador'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tarea.tarea'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
