# Generated by Django 4.0.4 on 2022-06-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0007_alter_produccion_empresa_alter_produccion_operacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='costeProd',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
