# Generated by Django 3.1.7 on 2021-07-10 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referencia', '0001_initial'),
        ('empresa', '0001_initial'),
        ('color', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_talla', models.CharField(max_length=20, unique=True)),
                ('nota', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Talla', to='empresa.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Talla', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom_talla'],
            },
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_operacion', models.CharField(max_length=20, unique=True)),
                ('estatus', models.CharField(choices=[('A', 'Activo'), ('C', 'Cerrado')], max_length=1)),
                ('cant_total', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Operacion', to='color.color')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Operacion', to='empresa.empresa')),
                ('referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Operacion', to='referencia.referencia')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Operacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom_operacion'],
            },
        ),
        migrations.CreateModel(
            name='CanTalla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_talla', models.IntegerField(blank=True, null=True)),
                ('res_talla', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CanTalla', to='empresa.empresa')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CanTalla', to='operacion.operacion')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CanTalla', to='operacion.talla')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CanTalla', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['talla'],
            },
        ),
    ]
