# Generated by Django 3.1.7 on 2021-07-11 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacion',
            old_name='cant_total',
            new_name='can_total',
        ),
    ]
