# Generated by Django 4.0.5 on 2022-06-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='btnTareaSeg',
            field=models.CharField(default='<button type="button" class="btn btn-outline-warning text-center btn-sm btn-block ">Tarea</button>', max_length=300),
        ),
    ]
