# Generated by Django 3.1.7 on 2022-05-07 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referencia', '0002_auto_20220506_2012'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Operacion', to='referencia.referencia'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Operacion', to='authapp.myuser'),
        ),
    ]
