# Generated by Django 4.0.4 on 2022-06-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='costeProd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
