# Generated by Django 3.1.7 on 2022-05-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
