# Generated by Django 4.0.4 on 2022-05-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0002_alter_operacion_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='nota',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
