# Generated by Django 3.1.7 on 2021-07-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0002_auto_20210710_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='btnAcci',
            field=models.CharField(blank=True, default='<button type="button" class="btn btn-outline-info icofont-dollar-true text-center btn-sm btn-block"></button>', max_length=500, null=True),
        ),
    ]
