# Generated by Django 4.0.5 on 2022-06-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0003_alter_operacion_btntareaseg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacion',
            name='btnTareaSeg',
        ),
        migrations.AddField(
            model_name='operacion',
            name='btnIntegraSegui',
            field=models.CharField(default='<button type="button" class="btn btn-outline-primary text-center btn-sm btn-block ">Integrantes</button>', max_length=300),
        ),
    ]
