# Generated by Django 3.1.7 on 2021-07-11 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0006_auto_20210710_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talla',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='talla',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='CanTalla',
        ),
        migrations.DeleteModel(
            name='Talla',
        ),
    ]
