# Generated by Django 3.1.7 on 2022-03-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambioempres',
            name='lastEm',
            field=models.IntegerField(default=1),
        ),
    ]
