# Generated by Django 3.1.7 on 2021-05-17 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relacionempresa',
            options={'ordering': ['id']},
        ),
    ]
