# Generated by Django 3.1.7 on 2022-02-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cambioempres',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['id']},
        ),
    ]
