# Generated by Django 4.0.4 on 2022-05-16 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_empresa_estatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relacionempresa',
            name='updated_at',
        ),
    ]
