# Generated by Django 4.0.4 on 2022-05-22 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0003_remove_relacionempresa_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cambioempres',
            old_name='Usuario',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='relacionempresa',
            name='Usuario',
        ),
        migrations.AddField(
            model_name='relacionempresa',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RelacionEmpresa', to=settings.AUTH_USER_MODEL),
        ),
    ]
