# Generated by Django 4.0.4 on 2022-05-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_rename_usuario_cambioempres_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nom_empresa',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
