# Generated by Django 3.1.7 on 2022-05-06 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tarea', '0002_auto_20220506_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='btnAcci',
            field=models.CharField(default='<button type="button" class="btn btn-outline-warning text-center btn-sm btn-block ">Accion</button>', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='btnInfo',
            field=models.CharField(default='<button type="button" class="btn    btn-outline-info text-center btn-sm btn-block">Info</button>', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tarea', to='authapp.myuser'),
        ),
    ]
