# Generated by Django 3.1.7 on 2021-07-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0002_tarea_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='btnAcci',
            field=models.CharField(blank=True, default='<button type="button" class="btn btn-outline-light text-center btn-sm btn-block ">Accion</button>', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='btnInfo',
            field=models.CharField(blank=True, default='<button type="button" class="btn    btn-outline-light text-center btn-sm btn-block">Info</button>', max_length=100, null=True),
        ),
    ]
