# Generated by Django 4.0.4 on 2022-05-18 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0003_tarea_fecha_cierre_alter_tarea_estatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_cierre',
        ),
    ]
