# Generated by Django 3.1.7 on 2021-07-12 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0003_auto_20210711_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='duracion',
            new_name='min_minuto',
        ),
    ]
