# Generated by Django 3.1.7 on 2022-05-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0004_auto_20220506_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='min_minuto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
