# Generated by Django 3.1.7 on 2021-07-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0004_auto_20210711_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='btnAcci',
            field=models.CharField(blank=True, default='<button type="button" class="btn btn-outline-info text-center btn-sm btn-block ">Accion</button>', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='btnInfo',
            field=models.CharField(blank=True, default='<button type="button" class="btn    btn-outline-info text-center btn-sm btn-block">Info</button>', max_length=100, null=True),
        ),
    ]
