# Generated by Django 3.1.7 on 2022-05-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0006_auto_20220506_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='codigo_tarea',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
